[package]
name = "replacer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
regex = "1.4.3"
glob = "0.3.0"
yew = "0.19"