name: Deploy
on:
  push:
    branches:
      - main
  # tags:
  # pull_request:
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_NET_GIT_FETCH_WITH_CLI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # rust compiler for running tests
      - uses: actions/checkout@v2
      - name: Install latest stable (for linux-gnu)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy
          # override: true
      # rust compiler for creating binaries
      - name: Install latest stable (for wasm)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          # override: true
      # caching (cargo registry)
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ubuntu-latest-stable-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
      # caching (cargo index)
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ubuntu-latest-stable-cargo-index-${{ hashFiles('**/Cargo.toml') }}
      - name: Install Trunk
        run: |
          set -e
          curl -L https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          mkdir trunk_bin
          mv trunk trunk_bin/trunk
          echo "`pwd`/trunk_bin" >> $GITHUB_PATH
      # based on
      # https://github.com/rustwasm/walrus/blob/9d6c9de432d6a97478dc76ebdf18aed51584c3af/.github/workflows/main.yml#L56
      - name: Install binaryen
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-linux.tar.gz | tar xzf -
          echo "`pwd`/binaryen-version_109/bin" >> $GITHUB_PATH
      - name: Trunk Build (Replacer)
        run: |
          set -e
          cd replacer/
          trunk build --release
      - name: Move and optimize assets
        run: |
          set -e
          mkdir -p publish/{replacer}
          mv -r replacer/dist/* publish/replacer
          find publish/ \
            -name \*.wasm \
            -prune \
            -exec wasm-opt -Oz -o "{}" "{}" \;
      - name: Frontend Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./publish
          keep_files: false
